# Generated by Django 4.2.7 on 2023-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("post", "0003_post_is_visible"),
        ("post", "0004_post_scheduled_time"),
    ]

    dependencies = [
        ("post", "0002_like_unique_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
