# Generated by Django 4.2.7 on 2023-11-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_alter_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="following",
        ),
        migrations.CreateModel(
            name="UserProfileFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userprofilefollow",
            constraint=models.UniqueConstraint(
                fields=("follower", "following"), name="unique_followers"
            ),
        ),
    ]
