# Generated by Django 4.2.7 on 2023-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_remove_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                fields=("created_by",), name="unique_created_by"
            ),
        ),
    ]
