# Generated by Django 4.2.7 on 2023-12-05 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0004_userprofile_unique_created_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprofilefollow",
            name="unique_followers",
        ),
        migrations.RemoveField(
            model_name="userprofilefollow",
            name="follower",
        ),
        migrations.AddField(
            model_name="userprofilefollow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.date(2023, 12, 5)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofilefollow",
            name="created_by",
            field=models.ForeignKey(
                default=datetime.date.today,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofilefollow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofilefollow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofilefollow",
            constraint=models.UniqueConstraint(
                fields=("created_by", "following"), name="unique_follows"
            ),
        ),
    ]
